09-rendering + 10-slots
js-tasks-ru/vue-20230710_mihail64 pull request #9
Opened 2023-08-22 12:37 UTC by m4ex

2023-08-22 12:38 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-08-23 21:37 UTC, ShGKme requested changes
Требуются исправления в задаче `09-rendering/02-TemplateRenderer`, остальные задачи приняты.

Была ли задача `09-rendering/03-UiPanes-JSX` особенно сложной и сложнее следующей?

2023-08-23 21:37 UTC, ShGKme commented on 09-rendering/01-VNode/components/VNode.vue
> +    return Array.isArray(this.vnode) ? [...this.vnode] : this.vnode;
Можно не клонировать массив, он не мутируется в рендер функции

2023-08-23 21:37 UTC, ShGKme commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +  },
Через `this.$options.components` мутируется описание компонента уже во время его работы. Это работает, но не очень чистое решение. 

Такое решение легко может сломаться при изменении внутренней работы Vue (он не гарантирует, что описание компонента используется не только при инициализации, но и во время работы. Например, если опция `component` будет клонироваться под капотом - всё сломается). 

Также это не позволяет двум экземплярам компонента передать разные `components` с одинаковыми именами. Новые экземпляры `TemplateRenderer` будут перебивать значения в старых, так как имеют общий объект зарегистрированных компонентов.

При этом при уничтожении экземпляра в `beforeDestroy` этот объект не чистится. Ссылки тут останутся, что может приводить к утечке памяти.

2023-08-23 21:37 UTC, ShGKme commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +import { compile } from 'vue/dist/vue.cjs';
Такое решение работает, но с таким решением в проекте будет одновременно две копии Vue - одна с компилятором и одна без компилятора. Вместо добавления двух копий лучше изменить конфигурацию сборки, чтобы использовалась версия с компилятором.

2023-08-23 21:37 UTC, ShGKme commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +  },
Вместо мутации описания компонента лучше создавать во время работы компонента новый компонент с определёнными зарегистрированными локальными компонентами и шаблоном (рендер функцией).

2023-08-23 21:37 UTC, ShGKme commented on 09-rendering/03-UiPanes-JSX/App.vue
> +      <!--  Default слот для теста, почему его тут не было сразу? Именовые слоты выше ведь не будут слотом по умолчанию -->
Спасибо за замечание, я добавлю здесь пример с default слотом как второй пример.

2023-08-23 21:37 UTC, ShGKme commented on 09-rendering/04-AdvancedUiTabs-JSX/components/UiTabs.vue
> +    const coreNodes = content.filter((node) => node.type === UiTab); //В принципе можно и не фильтровать, в входных данных и тестах корневой компонент всегда UiTab
Да, в задаче не учитывается, чтобы не перегружать.

В production лучше проверять.

2023-08-23 21:37 UTC, ShGKme commented on 09-rendering/04-AdvancedUiTabs-JSX/components/UiTabs.vue
> +              className={`tabs__tab ${this.activeTab === node.props.name ? 'tabs__tab_active':''}`}
В JSX также можно использовать синтаксис привязки классов объектом в обычном `class` атрибуте.

2023-08-23 21:37 UTC, ShGKme commented on 10-slots/02-PromiseWrapper/components/PromiseWrapper.vue
> +  </template>
Здесь лучше использовать цепочку с `v-else-if`, чтобы указывать Vue, что ровно 1 узел всегда рендерится, а не любое число от 0 до 3.

Либо использовать динамический `name` у слота.


Элемент `template` здесь лишний, условия можно устанавливать на сам `slot`

2023-08-23 21:37 UTC, ShGKme commented on 10-slots/03-UiCalendarView/components/MeetupsCalendar.vue
> +    </template>
Вызывать функцию полного перебора всех данных в шаблоне при рендеринге каждой ячейки при каждом ре-рендеринге - не оптимальное и не очень vue-way решение. Лучше готовить данные так, чтобы сразу можно было вывести данные ячейки в шаблоне.

2023-08-30 18:36 UTC, m4ex commented on 09-rendering/01-VNode/components/VNode.vue
> +    return Array.isArray(this.vnode) ? [...this.vnode] : this.vnode;
Убрал лишне, уже не помню почему так сначала написал

2023-08-30 18:52 UTC, m4ex commented on 10-slots/02-PromiseWrapper/components/PromiseWrapper.vue
> +  </template>
Согласен, поменял. В template я тут оборачивал потому что в предыдущей задаче у меня почему-то без template не работало. Хотя сейчас еще раз попробовал и в обоих случая вроде все работает. Вобщем убрал лишние секции template тут и в предыдущей задаче

2023-08-30 19:15 UTC, m4ex commented on 09-rendering/04-AdvancedUiTabs-JSX/components/UiTabs.vue
> +              className={`tabs__tab ${this.activeTab === node.props.name ? 'tabs__tab_active':''}`}
Поменял, с JSX раньше не работал. Гугл выдал это на запрос как прописать класс в JSX. Если какая-то разница или просто можно и так и так?

2023-08-30 19:18 UTC, m4ex commented on 10-slots/03-UiCalendarView/components/MeetupsCalendar.vue
> +    </template>
Согласен, оптимальней один раз переложить все в мапу с ключем по дате, как в самой первой реализации из предыдущей домашки. Суть я понял, но переделывать лениво.

2023-08-30 19:53 UTC, m4ex commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +import { compile } from 'vue/dist/vue.cjs';
Прописал в vite.config.js в секцию resolve->alias :
`{ find: 'vue', replacement: 'vue/dist/vue.esm-bundler' }`
Так нужно было сделать? Но у нас же так поменяется версия vue для всего проекта, а версия с компилятором нужна только в этой конкретной задаче.

Кстати, а если версию  во всех файлах в папке 02-TemplateRenderer подгружать все из vue/dist/vue.cjs все равно 2 версии будет или тогда везде одна. В том какие именно бывают версии я как-то не до конца разобрался. Чем например отличается vue/dist/vue.esm-bundler от vue/dist/vue.cjs? Если первую указать не в конфиге - работает,  а если просто загрузить из vue файла - не работает.

2023-08-30 20:18 UTC, ShGKme commented on 09-rendering/04-AdvancedUiTabs-JSX/components/UiTabs.vue
> +              className={`tabs__tab ${this.activeTab === node.props.name ? 'tabs__tab_active':''}`}
`className` ввели в JSX в React.js, чтобы не пересекаться с `class` в JS и не было проблем из-за этого. Но это не приводит к проблемам, во Vue оставили возможность использовать просто `class`.

2023-08-30 20:22 UTC, ShGKme commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +import { compile } from 'vue/dist/vue.cjs';
> Так нужно было сделать? 

Да

> Но у нас же так поменяется версия vue для всего проекта, а версия с компилятором нужна только в этой конкретной задаче.

Верно, но считая это одним большим проектом - проще всем дать маленький компилятор, чем добавить отдельной части свою копию Vue с компилятором.

> Кстати, а если версию во всех файлах в папке 02-TemplateRenderer подгружать все из vue/dist/vue.cjs все равно 2 версии будет или тогда везде одна.

Будет одна, но лучше подгружать esm версию. Иначе Vite просто сам чуть потратит время, чтобы из vue.cjs собрать esm версию, так как Vite работает только в ES модулях.

> Чем например отличается vue/dist/vue.esm-bundler от vue/dist/vue.cjs

Первая - ES Module для Node.js (и сборщиков), второй - CommonJS Module для Node.js (и сборщиков).
Отличаются только типом модуля. Обе версии - полные, с компилятором. Обе подходят для разработки и прода (в версиях для Node.js разделение на prod и dev осуществляется с помощью переменных окружения)

2023-08-30 20:22 UTC, ShGKme commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +import { compile } from 'vue/dist/vue.cjs';
Возможно, я был не совсем прав, и если импортировать только компилятор с `{ compile }`, то лишней версии Vue не будет. Нужно проверить.

2023-08-31 10:42 UTC, m4ex commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +  },
Тут пока все никак не могу разобраться, нужна помощь. Не понимаю как сделать динамическое создание компонента. Что оно должно делать я понимаю, но как это в коде описать не понятно. Примеров как делать такое не нашел, по каким ключевым словам искать? По dynamic component выдает только про  <component :is=..> и defineAsyncComponent возможно все таки нужно прикрутить второе, но в примерах из документации оно используется только на верхнем уровне с createApp и app.component

2023-08-31 10:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-31 18:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-31 18:03 UTC, m4ex commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +  },
В итоге наконец-то получилось

2023-08-31 18:11 UTC, m4ex commented
> Была ли задача 09-rendering/03-UiPanes-JSX особенно сложной и сложнее следующей?
Да вроде нет, у меня с ней на сколько я помню особо проблем не возникло.

09-rendering/02-TemplateRenderer в итоге вроде победил

2023-09-05 08:57 UTC, m4ex commented
На всякий случай подсвечу что тесты тут фейлятся уже от следующих заданий

2023-09-05 10:45 UTC, ShGKme commented on 09-rendering/02-TemplateRenderer/components/TemplateRenderer.vue
> +  },
Здесь в качестве рендер функции используется не просто скомпилированный шаблон, а функция, которая компилирует шаблон и вызывает его с `bindings`.

В итоге:
1. При каждом рендеринге заново компилируется шаблон (это медленно)
2. Изменение данных для шаблона требует компиляции шаблона и даже заново создавать этот временный компонент.

Одновременно и создавать промежуточный компонент, и передавать в него данные - не оптимально.  В отличие от шаблона, данные могут меняться часто.

Вместо этого лучше в `dynamicComponent` только генерировать компонент с рендер функцией из шаблона, а уже при его рендеринге, в `return h(this.dynamicComponent)` передавать в него данные из `binding`

2023-09-05 12:07 UTC, m4ex commented
https://github.com/js-tasks-ru/vue-20230710_mihail64/pull/13

2023-09-05 12:07 UTC, closed without merging